services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "14000:5432"
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
